/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2026-04-02 13:55:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import jakarta.servlet.http.HttpSession;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("jakarta.servlet.http.HttpSession");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    // Already logged in? Go to inbox
    if (session != null && session.getAttribute("user") != null) {
        response.sendRedirect(request.getContextPath() + "/mail/inbox");
        return;
    }
    String error   = (String) session.getAttribute("error");
    String success = (String) session.getAttribute("success");
    session.removeAttribute("error");
    session.removeAttribute("success");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>JavaMail — Sign In</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/style.css\">\n");
      out.write("  <link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>✉</text></svg>\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"auth-root\">\n");
      out.write("\n");
      out.write("  <!-- ── Left: Form ────────────────────────────── -->\n");
      out.write("  <div class=\"auth-panel\">\n");
      out.write("    <div class=\"auth-brand\">\n");
      out.write("      <div class=\"auth-brand-icon\">✉</div>\n");
      out.write("      <span class=\"auth-brand-name\">JavaMail</span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <h1 class=\"auth-heading\">Welcome back</h1>\n");
      out.write("    <p class=\"auth-sub\">Sign in to your account to continue</p>\n");
      out.write("\n");
      out.write("    ");
 if (error != null) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-error\">⚠ ");
      out.print( error );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if (success != null) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-success\">✓ ");
      out.print( success );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/user/login\" method=\"POST\">\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label class=\"form-label\">Email address</label>\n");
      out.write("        <input class=\"form-input\" type=\"email\" name=\"email\" placeholder=\"you@example.com\" required autofocus>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"form-group\">\n");
      out.write("        <label class=\"form-label\">Password</label>\n");
      out.write("        <input class=\"form-input\" type=\"password\" name=\"password\" placeholder=\"Your password\" required>\n");
      out.write("      </div>\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary btn-full\" style=\"margin-top:8px;\">\n");
      out.write("        Sign In →\n");
      out.write("      </button>\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <div class=\"auth-footer\">\n");
      out.write("      Don't have an account? <a href=\"");
      out.print( request.getContextPath() );
      out.write("/register.jsp\">Create one</a>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- ── Right: Visual ─────────────────────────── -->\n");
      out.write("  <div class=\"auth-visual\">\n");
      out.write("    <div class=\"auth-visual-glow\"></div>\n");
      out.write("    <div class=\"auth-visual-title\">Your inbox,<br>reimagined.</div>\n");
      out.write("    <div class=\"auth-visual-sub\">\n");
      out.write("      A fast, powerful email client built entirely in Java — with a clean interface, full JDBC persistence, and every feature you need.\n");
      out.write("    </div>\n");
      out.write("    <div class=\"auth-features\">\n");
      out.write("      <div class=\"auth-feature\">\n");
      out.write("        <div class=\"auth-feature-icon\">📥</div>\n");
      out.write("        <div class=\"auth-feature-text\">\n");
      out.write("          <strong>Smart Inbox</strong>\n");
      out.write("          Unread counts, star, and important flags keep you on top of everything\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"auth-feature\">\n");
      out.write("        <div class=\"auth-feature-icon\">⚡</div>\n");
      out.write("        <div class=\"auth-feature-text\">\n");
      out.write("          <strong>JDBC Backed</strong>\n");
      out.write("          All data persisted to MySQL via PreparedStatements — fully production-ready\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"auth-feature\">\n");
      out.write("        <div class=\"auth-feature-icon\">🔒</div>\n");
      out.write("        <div class=\"auth-feature-text\">\n");
      out.write("          <strong>Secure Auth</strong>\n");
      out.write("          SHA-256 hashed passwords and session management built in\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/app.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
