/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2026-04-02 13:56:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.javamail.model.Mail;
import com.javamail.model.User;

public final class compose_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.javamail.model.Mail");
    _jspx_imports_classes.add("com.javamail.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User currUser = (User) session.getAttribute("user");
    if (currUser == null) { response.sendRedirect(request.getContextPath() + "/login.jsp"); return; }

    String ctx         = request.getContextPath();
    String composeMode = (String) request.getAttribute("composeMode");
    Mail   original    = (Mail)   request.getAttribute("original");
    Mail   prefill     = (Mail)   request.getAttribute("prefill");
    if (composeMode == null) composeMode = "compose";

    String headingText;
    switch (composeMode) {
        case "reply":
            headingText = "Reply";
            break;
        case "forward":
            headingText = "Forward";
            break;
        default:
            headingText = "New Mail";
    }

    // Pre-fill fields
    String toVal      = "";
    String subjectVal = "";
    String bodyVal    = "";

    if ("reply".equals(composeMode) && original != null) {
        toVal      = original.getFromEmail();
        subjectVal = "Re: " + original.getSubject();
        bodyVal    = "\n\n--- Original message ---\nFrom: " + original.getFromEmail()
                   + "\nDate: " + original.getFormattedDate()
                   + "\n\n" + original.getBody();
    } else if ("forward".equals(composeMode) && original != null) {
        subjectVal = "Fwd: " + original.getSubject();
        bodyVal    = "\n\n--- Forwarded message ---\nFrom: " + original.getFromEmail()
                   + "\nDate: " + original.getFormattedDate()
                   + "\n\n" + original.getBody();
    } else if (prefill != null) {
        toVal      = prefill.getToEmail()  != null ? prefill.getToEmail()  : "";
        subjectVal = prefill.getSubject()  != null ? prefill.getSubject()  : "";
        bodyVal    = prefill.getBody()     != null ? prefill.getBody()     : "";
    }

    String error   = (String) session.getAttribute("error");
    session.removeAttribute("error");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>");
      out.print( headingText );
      out.write(" — JavaMail</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/css/style.css\">\n");
      out.write("  <script>const contextPath = \"");
      out.print( ctx );
      out.write("\";</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"app-shell\">\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"main-content\">\n");
      out.write("    <!-- Topbar -->\n");
      out.write("    <div class=\"topbar\">\n");
      out.write("      <a href=\"javascript:history.back()\" class=\"btn btn-ghost btn-sm\">← Back</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"compose-area\">\n");
      out.write("      <div class=\"compose-heading\">✏ ");
      out.print( headingText );
      out.write("</div>\n");
      out.write("\n");
      out.write("      ");
 if (error != null) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-error\" style=\"margin-bottom:16px;\">⚠ ");
      out.print( error );
      out.write("</div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"compose-form-card\">\n");
      out.write("\n");
      out.write("        <!-- From (read-only) -->\n");
      out.write("        <div class=\"compose-field\">\n");
      out.write("          <span class=\"compose-field-label\">From</span>\n");
      out.write("          <input type=\"text\" value=\"");
      out.print( currUser.getEmail() );
      out.write("\" readonly\n");
      out.write("                 style=\"color:var(--text-muted);cursor:default;\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- To -->\n");
      out.write("        <div class=\"compose-field\">\n");
      out.write("          <span class=\"compose-field-label\">To</span>\n");
      out.write("          <input type=\"email\" id=\"to-field\" name=\"to\" form=\"mail-form\"\n");
      out.write("                 value=\"");
      out.print( toVal );
      out.write("\"\n");
      out.write("                 placeholder=\"recipient@example.com\" required\n");
      out.write("                 ");
      out.print( "reply".equals(composeMode) ? "" : "" );
      out.write(">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- CC (collapsible) -->\n");
      out.write("        <div class=\"compose-field\" id=\"cc-row\" style=\"display:none;\">\n");
      out.write("          <span class=\"compose-field-label\">CC</span>\n");
      out.write("          <input type=\"email\" name=\"cc\" form=\"mail-form\" placeholder=\"cc@example.com\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- BCC (collapsible) -->\n");
      out.write("        <div class=\"compose-field\" id=\"bcc-row\" style=\"display:none;\">\n");
      out.write("          <span class=\"compose-field-label\">BCC</span>\n");
      out.write("          <input type=\"email\" name=\"bcc\" form=\"mail-form\" placeholder=\"bcc@example.com\">\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Subject -->\n");
      out.write("        <div class=\"compose-field\">\n");
      out.write("          <span class=\"compose-field-label\">Subject</span>\n");
      out.write("          <input type=\"text\" name=\"subject\" form=\"mail-form\"\n");
      out.write("                 value=\"");
      out.print( subjectVal );
      out.write("\"\n");
      out.write("                 placeholder=\"Subject\" required>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Body -->\n");
      out.write("        <div class=\"compose-field\" style=\"border-bottom:none;\">\n");
      out.write("          <span class=\"compose-field-label\" style=\"padding-top:16px;\">Body</span>\n");
      out.write("          <textarea name=\"body\" form=\"mail-form\"\n");
      out.write("                    placeholder=\"Write your message here…\"\n");
      out.write("                    id=\"mail-body\">");
      out.print( bodyVal );
      out.write("</textarea>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Toolbar -->\n");
      out.write("        <div class=\"compose-toolbar\">\n");
      out.write("          <!-- CC / BCC toggles -->\n");
      out.write("          <button type=\"button\" class=\"btn btn-ghost btn-sm\" onclick=\"toggleField('cc-row')\">+ CC</button>\n");
      out.write("          <button type=\"button\" class=\"btn btn-ghost btn-sm\" onclick=\"toggleField('bcc-row')\">+ BCC</button>\n");
      out.write("\n");
      out.write("          <div style=\"margin-left:auto;display:flex;gap:8px;\">\n");
      out.write("            <!-- Save Draft -->\n");
      out.write("            <button type=\"button\" id=\"save-draft-btn\" class=\"btn btn-secondary btn-sm\"\n");
      out.write("                    onclick=\"submitForm('draft')\">💾 Save Draft</button>\n");
      out.write("            <!-- Send -->\n");
      out.write("            <button type=\"submit\" form=\"mail-form\" class=\"btn btn-primary btn-sm\">\n");
      out.write("              📤 Send\n");
      out.write("            </button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div><!-- /compose-form-card -->\n");
      out.write("\n");
      out.write("      <!-- Actual form (outside card so button can submit it) -->\n");
      out.write("      <form id=\"mail-form\" action=\"");
      out.print( ctx );
      out.write("/mail/send\" method=\"POST\" style=\"display:none;\">\n");
      out.write("        <input type=\"hidden\" name=\"_action\" id=\"form-action\" value=\"send\">\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("    </div><!-- /compose-area -->\n");
      out.write("  </div><!-- /main-content -->\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print( ctx );
      out.write("/js/app.js\"></script>\n");
      out.write("<script>\n");
      out.write("function toggleField(id) {\n");
      out.write("  const row = document.getElementById(id);\n");
      out.write("  row.style.display = row.style.display === 'none' ? 'flex' : 'none';\n");
      out.write("}\n");
      out.write("\n");
      out.write("function submitForm(action) {\n");
      out.write("  const form = document.getElementById('mail-form');\n");
      out.write("  if (action === 'draft') {\n");
      out.write("    form.action = contextPath + '/mail/draft/save';\n");
      out.write("  } else {\n");
      out.write("    form.action = contextPath + '/mail/send';\n");
      out.write("  }\n");
      out.write("  // Copy inline inputs to hidden form\n");
      out.write("  ['to', 'cc', 'bcc', 'subject', 'body'].forEach(name => {\n");
      out.write("    let src = document.querySelector(`[name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"]`);\n");
      out.write("    if (!src) src = document.getElementById(name === 'body' ? 'mail-body' : name + '-field');\n");
      out.write("    if (src) {\n");
      out.write("      let inp = form.querySelector(`[name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"]`);\n");
      out.write("      if (!inp) {\n");
      out.write("        inp = document.createElement('input');\n");
      out.write("        inp.type  = 'hidden';\n");
      out.write("        inp.name  = name;\n");
      out.write("        form.appendChild(inp);\n");
      out.write("      }\n");
      out.write("      inp.value = src.value;\n");
      out.write("    }\n");
      out.write("  });\n");
      out.write("  form.submit();\n");
      out.write("}\n");
      out.write("\n");
      out.write("// Override send button to go through submitForm\n");
      out.write("document.getElementById('mail-form').addEventListener('submit', function(e) {\n");
      out.write("  e.preventDefault();\n");
      out.write("  submitForm('send');\n");
      out.write("});\n");
      out.write("\n");
      out.write("// Also make inline inputs submit via submitForm on Enter in To/Subject fields\n");
      out.write("['to', 'subject'].forEach(id => {\n");
      out.write("  const el = document.querySelector(`[name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"]`);\n");
      out.write("  if (el) el.addEventListener('keydown', e => {\n");
      out.write("    if (e.key === 'Enter') { e.preventDefault(); submitForm('send'); }\n");
      out.write("  });\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
