/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2026-04-02 13:55:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.javamail.model.Mail;
import com.javamail.model.User;
import java.util.List;

public final class mailbox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.javamail.model.Mail");
    _jspx_imports_classes.add("com.javamail.model.User");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User   currUser = (User)   session.getAttribute("user");
    if (currUser == null) { response.sendRedirect(request.getContextPath() + "/login.jsp"); return; }

    List<Mail> mails  = (List<Mail>) request.getAttribute("mails");
    String folder     = (String)     request.getAttribute("folder");
    String query      = (String)     request.getAttribute("query");
    int    unread     = (request.getAttribute("unread") instanceof Integer) ? (Integer) request.getAttribute("unread") : 0;
    String ctx        = request.getContextPath();

    String folderTitle;
    switch (folder != null ? folder : "") {
        case "inbox":
            folderTitle = "Inbox";
            break;
        case "sent":
            folderTitle = "Sent";
            break;
        case "draft":
            folderTitle = "Drafts";
            break;
        case "trash":
            folderTitle = "Trash";
            break;
        case "spam":
            folderTitle = "Spam";
            break;
        case "starred":
            folderTitle = "Starred";
            break;
        case "important":
            folderTitle = "Important";
            break;
        case "search":
            folderTitle = "Search Results";
            break;
        default:
            folderTitle = "Mails";
    }

    String success = (String) session.getAttribute("success");
    String error   = (String) session.getAttribute("error");
    session.removeAttribute("success");
    session.removeAttribute("error");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>");
      out.print( folderTitle );
      out.write(" — JavaMail</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/css/style.css\">\n");
      out.write("  <script>const contextPath = \"");
      out.print( ctx );
      out.write("\";</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"app-shell\">\n");
      out.write("\n");
      out.write("  <!-- Sidebar -->\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("  <!-- Main -->\n");
      out.write("  <div class=\"main-content\">\n");
      out.write("\n");
      out.write("    <!-- Topbar -->\n");
      out.write("    <div class=\"topbar\">\n");
      out.write("      <span class=\"topbar-folder\">");
      out.print( folderTitle );
      out.write("</span>\n");
      out.write("\n");
      out.write("      <form class=\"search-bar\" action=\"");
      out.print( ctx );
      out.write("/mail/search\" method=\"GET\">\n");
      out.write("        <span class=\"search-icon\">🔍</span>\n");
      out.write("        <input type=\"text\" name=\"q\" placeholder=\"Search mails…\"\n");
      out.write("               value=\"");
      out.print( query != null ? query : "" );
      out.write("\"\n");
      out.write("               onkeypress=\"submitSearch(event)\">\n");
      out.write("      </form>\n");
      out.write("\n");
      out.write("      <div class=\"topbar-actions\">\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/mail/compose\" class=\"btn btn-primary btn-sm\">✏ Compose</a>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Flash messages -->\n");
      out.write("    ");
 if (success != null) { 
      out.write("\n");
      out.write("      <div style=\"padding:0 24px;margin-top:12px;\">\n");
      out.write("        <div class=\"alert alert-success\">✓ ");
      out.print( success );
      out.write("</div>\n");
      out.write("      </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if (error != null) { 
      out.write("\n");
      out.write("      <div style=\"padding:0 24px;margin-top:12px;\">\n");
      out.write("        <div class=\"alert alert-error\">⚠ ");
      out.print( error );
      out.write("</div>\n");
      out.write("      </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Mail list -->\n");
      out.write("    <div class=\"mail-list-area\">\n");
      out.write("\n");
      out.write("      <!-- List header with bulk actions -->\n");
      out.write("      <div class=\"mail-list-header\">\n");
      out.write("        <input type=\"checkbox\" class=\"checkbox-custom\" id=\"select-all\" onchange=\"toggleSelectAll(this)\" title=\"Select all\">\n");
      out.write("        <span class=\"mail-count\">\n");
      out.write("          ");
 if (mails != null) { 
      out.write("\n");
      out.write("            ");
      out.print( mails.size() );
      out.write(" mail");
      out.print( mails.size() != 1 ? "s" : "" );
      out.write("\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </span>\n");
      out.write("\n");
      out.write("        <!-- Bulk actions (hidden until selection) -->\n");
      out.write("        <div id=\"bulk-actions\" style=\"display:none; align-items:center; gap:8px;\">\n");
      out.write("          <span id=\"selected-count\" style=\"font-size:12px;color:var(--text-secondary);\"></span>\n");
      out.write("          ");
 if (!"trash".equals(folder)) { 
      out.write("\n");
      out.write("          <button class=\"btn btn-ghost btn-sm\" onclick=\"bulkAction('delete')\">🗑 Delete</button>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          ");
 if ("trash".equals(folder)) { 
      out.write("\n");
      out.write("          <button class=\"btn btn-ghost btn-sm\" onclick=\"bulkAction('restore')\">↩ Restore</button>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          <button class=\"btn btn-ghost btn-sm\" onclick=\"bulkAction('star')\">⭐ Star</button>\n");
      out.write("          <button class=\"btn btn-ghost btn-sm\" onclick=\"bulkAction('spam')\">🚫 Spam</button>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"mail-list-header-actions\" style=\"margin-left:auto;\">\n");
      out.write("          ");
 if ("trash".equals(folder) && mails != null && !mails.isEmpty()) { 
      out.write("\n");
      out.write("            <button class=\"btn btn-danger btn-sm\" onclick=\"confirmEmptyTrash()\">🗑 Empty Trash</button>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          <button class=\"btn btn-ghost btn-sm\" onclick=\"location.reload()\" title=\"Refresh\">↻</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- Search label -->\n");
      out.write("      ");
 if ("search".equals(folder) && query != null) { 
      out.write("\n");
      out.write("        <div style=\"padding:12px 24px;font-size:13px;color:var(--text-secondary);border-bottom:1px solid var(--border-soft);\">\n");
      out.write("          Results for <strong style=\"color:var(--text-primary);\">\"");
      out.print( query );
      out.write("\"</strong>\n");
      out.write("        </div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      <!-- Mail rows -->\n");
      out.write("      ");
 if (mails == null || mails.isEmpty()) { 
      out.write("\n");
      out.write("        <div class=\"empty-state\">\n");
      out.write("          <div class=\"empty-icon\">\n");
      out.write("            ");
      out.print( "inbox".equals(folder) ? "📭" : "trash".equals(folder) ? "🗑" : "draft".equals(folder) ? "📝" : "📭" );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"empty-title\">\n");
      out.write("            ");
      out.print( "search".equals(folder) ? "No results found" : "Nothing here" );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div class=\"empty-sub\">\n");
      out.write("            ");
      out.print( "inbox".equals(folder) ? "Your inbox is all clear!" :
                "search".equals(folder) ? "Try a different search term." :
                "This folder is empty." );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          ");
 if ("inbox".equals(folder)) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/mail/compose\" class=\"btn btn-primary btn-sm\" style=\"margin-top:8px;\">✏ Compose a mail</a>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      ");
 } else { 
      out.write("\n");
      out.write("        ");
 for (Mail mail : mails) {
            boolean isUnread = !mail.isRead();
            String senderDisplay = (mail.getFromUsername() != null && !mail.getFromUsername().isEmpty())
                                   ? mail.getFromUsername() : mail.getFromEmail();
            boolean isMine = currUser.getEmail().equals(mail.getFromEmail());
            String displayName = isMine ? ("To: " + mail.getToEmail()) : senderDisplay;
        
      out.write("\n");
      out.write("        <div class=\"mail-item ");
      out.print( isUnread ? "unread" : "" );
      out.write("\">\n");
      out.write("          <!-- Checkbox -->\n");
      out.write("          <input type=\"checkbox\" class=\"checkbox-custom mail-checkbox\"\n");
      out.write("                 data-mail-id=\"");
      out.print( mail.getId() );
      out.write("\"\n");
      out.write("                 onchange=\"toggleMailSelect(this, ");
      out.print( mail.getId() );
      out.write(")\">\n");
      out.write("\n");
      out.write("          <!-- Avatar -->\n");
      out.write("          <div class=\"mail-item-avatar\"\n");
      out.write("               data-email-avatar=\"");
      out.print( mail.getFromEmail() );
      out.write("\"\n");
      out.write("               data-name=\"");
      out.print( senderDisplay );
      out.write("\">\n");
      out.write("            ");
      out.print( senderDisplay.substring(0,1).toUpperCase() );
      out.write("\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <!-- Main content (clickable) -->\n");
      out.write("          <a href=\"");
      out.print( ctx );
      out.write("/mail/view?id=");
      out.print( mail.getId() );
      out.write("\" class=\"mail-item-main\" style=\"display:block;flex:1;min-width:0;\">\n");
      out.write("            <div class=\"mail-item-top\">\n");
      out.write("              <span class=\"mail-item-sender\">");
      out.print( displayName );
      out.write("</span>\n");
      out.write("              <span class=\"mail-item-subject\">— ");
      out.print( mail.getSubject() );
      out.write("</span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mail-item-preview\">");
      out.print( mail.getPreview() );
      out.write("</div>\n");
      out.write("          </a>\n");
      out.write("\n");
      out.write("          <!-- Meta -->\n");
      out.write("          <div class=\"mail-item-meta\">\n");
      out.write("            <span class=\"mail-item-date\">");
      out.print( mail.getFormattedDate() );
      out.write("</span>\n");
      out.write("            <div class=\"mail-item-icons\">\n");
      out.write("              <!-- Star -->\n");
      out.write("              <button class=\"icon-btn ");
      out.print( mail.isStarred() ? "starred" : "" );
      out.write("\"\n");
      out.write("                      title=\"");
      out.print( mail.isStarred() ? "Unstar" : "Star" );
      out.write("\"\n");
      out.write("                      onclick=\"toggleStar(this, ");
      out.print( mail.getId() );
      out.write(")\">⭐</button>\n");
      out.write("              <!-- Important -->\n");
      out.write("              <button class=\"icon-btn ");
      out.print( mail.isImportant() ? "important" : "" );
      out.write("\"\n");
      out.write("                      title=\"");
      out.print( mail.isImportant() ? "Unmark" : "Mark important" );
      out.write("\"\n");
      out.write("                      onclick=\"toggleImportant(this, ");
      out.print( mail.getId() );
      out.write(")\">🔖</button>\n");
      out.write("              <!-- Delete / Restore -->\n");
      out.write("              ");
 if ("trash".equals(folder)) { 
      out.write("\n");
      out.write("                <form method=\"POST\" action=\"");
      out.print( ctx );
      out.write("/mail/restore\" style=\"display:inline;\">\n");
      out.write("                  <input type=\"hidden\" name=\"mailId\" value=\"");
      out.print( mail.getId() );
      out.write("\">\n");
      out.write("                  <input type=\"hidden\" name=\"redirect\" value=\"trash\">\n");
      out.write("                  <button type=\"submit\" class=\"icon-btn\" title=\"Restore\">↩</button>\n");
      out.write("                </form>\n");
      out.write("              ");
 } else { 
      out.write("\n");
      out.write("                <button class=\"icon-btn\" title=\"Delete\"\n");
      out.write("                        onclick=\"confirmDelete(");
      out.print( mail.getId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( folder );
      out.write("')\">🗑</button>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </div><!-- /mail-list-area -->\n");
      out.write("\n");
      out.write("  </div><!-- /main-content -->\n");
      out.write("</div><!-- /app-shell -->\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print( ctx );
      out.write("/js/app.js\"></script>\n");
      out.write("<script>\n");
      out.write("// Bulk action helper\n");
      out.write("function bulkAction(action) {\n");
      out.write("  if (selectedMails.size === 0) return;\n");
      out.write("  if (!confirm(`Apply \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${action}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" to ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedMails.size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" mail(s)?`)) return;\n");
      out.write("  const ids = Array.from(selectedMails);\n");
      out.write("  ids.forEach(id => {\n");
      out.write("    fetch(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mail/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${action}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, {\n");
      out.write("      method: 'POST',\n");
      out.write("      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },\n");
      out.write("      body: `mailId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&redirect=");
      out.print( folder );
      out.write("`\n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("  setTimeout(() => location.reload(), 600);\n");
      out.write("}\n");
      out.write("\n");
      out.write("// Show flash toasts\n");
 if (success != null) { 
      out.write("\n");
      out.write("  document.addEventListener('DOMContentLoaded', () => Toast.success(\"");
      out.print( success );
      out.write("\"));\n");
 } 
      out.write('\n');
 if (error != null) { 
      out.write("\n");
      out.write("  document.addEventListener('DOMContentLoaded', () => Toast.error(\"");
      out.print( error );
      out.write("\"));\n");
 } 
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
