/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2026-04-02 14:00:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.javamail.model.User;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.javamail.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User currUser = (User) session.getAttribute("user");
    if (currUser == null) { response.sendRedirect(request.getContextPath() + "/login.jsp"); return; }

    String ctx     = request.getContextPath();
    String success = (String) session.getAttribute("success");
    String error   = (String) session.getAttribute("error");
    session.removeAttribute("success");
    session.removeAttribute("error");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Profile — JavaMail</title>\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( ctx );
      out.write("/css/style.css\">\n");
      out.write("  <script>const contextPath = \"");
      out.print( ctx );
      out.write("\";</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"app-shell\">\n");
      out.write("  ");
      out.write('\n');
      out.write(' ');
      out.write(' ');
 request.setAttribute("folder","profile"); request.setAttribute("unread",0); 
      out.write('\n');
      out.write(' ');
      out.write(' ');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("  <div class=\"main-content\">\n");
      out.write("    <div class=\"topbar\">\n");
      out.write("      <span class=\"topbar-folder\">Profile & Settings</span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"profile-area\">\n");
      out.write("      <div class=\"profile-heading\">👤 My Profile</div>\n");
      out.write("\n");
      out.write("      ");
 if (success != null) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-success\">✓ ");
      out.print( success );
      out.write("</div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("      ");
 if (error != null) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-error\">⚠ ");
      out.print( error );
      out.write("</div>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("      <!-- ── Avatar + Name card ─────────────────────── -->\n");
      out.write("      <div class=\"profile-card\" style=\"display:flex;align-items:center;gap:20px;\">\n");
      out.write("        <div style=\"width:72px;height:72px;border-radius:50%;background:var(--accent);\n");
      out.write("                    display:flex;align-items:center;justify-content:center;\n");
      out.write("                    font-size:28px;font-weight:700;color:#fff;flex-shrink:0;\"\n");
      out.write("             data-email-avatar=\"");
      out.print( currUser.getEmail() );
      out.write("\"\n");
      out.write("             data-name=\"");
      out.print( currUser.getUsername() );
      out.write("\">\n");
      out.write("          ");
      out.print( currUser.getUsername().substring(0,1).toUpperCase() );
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <div>\n");
      out.write("          <div style=\"font-family:'Syne',sans-serif;font-size:20px;font-weight:700;margin-bottom:4px;\">\n");
      out.write("            ");
      out.print( currUser.getUsername() );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div style=\"color:var(--text-secondary);font-size:14px;\">\n");
      out.write("            ");
      out.print( currUser.getEmail() );
      out.write("\n");
      out.write("          </div>\n");
      out.write("          <div style=\"color:var(--text-muted);font-size:12px;margin-top:4px;\">\n");
      out.write("            Member since ");
      out.print( currUser.getCreatedAt() != null
              ? new java.text.SimpleDateFormat("MMMM yyyy").format(currUser.getCreatedAt())
              : "—" );
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- ── Edit Profile ─────────────────────────────── -->\n");
      out.write("      <div class=\"profile-card\">\n");
      out.write("        <div class=\"profile-card-title\">Edit Profile</div>\n");
      out.write("        <form action=\"");
      out.print( ctx );
      out.write("/user/profile\" method=\"POST\">\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"form-label\">Full Name</label>\n");
      out.write("            <input class=\"form-input\" type=\"text\" name=\"username\"\n");
      out.write("                   value=\"");
      out.print( currUser.getUsername() );
      out.write("\" required>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-row\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label class=\"form-label\">Date of Birth</label>\n");
      out.write("              <input class=\"form-input\" type=\"date\" name=\"dob\"\n");
      out.write("                     value=\"");
      out.print( currUser.getDob() != null ? currUser.getDob() : "" );
      out.write("\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <label class=\"form-label\">Contact Number</label>\n");
      out.write("              <input class=\"form-input\" type=\"tel\" name=\"contact\"\n");
      out.write("                     value=\"");
      out.print( currUser.getContact() != null ? currUser.getContact() : "" );
      out.write("\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"form-label\">Email Address</label>\n");
      out.write("            <input class=\"form-input\" type=\"email\" value=\"");
      out.print( currUser.getEmail() );
      out.write("\" readonly\n");
      out.write("                   style=\"color:var(--text-muted);cursor:not-allowed;\">\n");
      out.write("            <small style=\"color:var(--text-muted);font-size:11px;\">Email cannot be changed.</small>\n");
      out.write("          </div>\n");
      out.write("          <button type=\"submit\" class=\"btn btn-primary\">Save Changes</button>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- ── Change Password ──────────────────────────── -->\n");
      out.write("      <div class=\"profile-card\">\n");
      out.write("        <div class=\"profile-card-title\">Change Password</div>\n");
      out.write("        <form action=\"");
      out.print( ctx );
      out.write("/user/password\" method=\"POST\">\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"form-label\">Current Password</label>\n");
      out.write("            <input class=\"form-input\" type=\"password\" name=\"currentPassword\" required\n");
      out.write("                   placeholder=\"Your current password\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"form-label\">New Password</label>\n");
      out.write("            <input class=\"form-input\" type=\"password\" name=\"newPassword\" required\n");
      out.write("                   placeholder=\"New password (min 6 chars)\" minlength=\"6\" id=\"new-pass\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label class=\"form-label\">Confirm New Password</label>\n");
      out.write("            <input class=\"form-input\" type=\"password\" name=\"confirmPassword\" required\n");
      out.write("                   placeholder=\"Repeat new password\" id=\"confirm-pass\">\n");
      out.write("          </div>\n");
      out.write("          <button type=\"submit\" class=\"btn btn-primary\">Update Password</button>\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- ── Account Stats ────────────────────────────── -->\n");
      out.write("      <div class=\"profile-card\">\n");
      out.write("        <div class=\"profile-card-title\">Account Info</div>\n");
      out.write("        <div style=\"display:grid;grid-template-columns:1fr 1fr;gap:16px;\">\n");
      out.write("          <div style=\"background:var(--bg-2);border:1px solid var(--border);border-radius:var(--radius);padding:16px;text-align:center;\">\n");
      out.write("            <div style=\"font-family:'Syne',sans-serif;font-size:28px;font-weight:800;color:var(--accent);\">∞</div>\n");
      out.write("            <div style=\"font-size:12px;color:var(--text-muted);margin-top:4px;\">Storage</div>\n");
      out.write("          </div>\n");
      out.write("          <div style=\"background:var(--bg-2);border:1px solid var(--border);border-radius:var(--radius);padding:16px;text-align:center;\">\n");
      out.write("            <div style=\"font-family:'Syne',sans-serif;font-size:28px;font-weight:800;color:var(--green);\">✓</div>\n");
      out.write("            <div style=\"font-size:12px;color:var(--text-muted);margin-top:4px;\">Account Active</div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- ── Danger Zone ──────────────────────────────── -->\n");
      out.write("      <div class=\"profile-card\" style=\"border-color:rgba(245,91,91,.25);\">\n");
      out.write("        <div class=\"profile-card-title\" style=\"color:var(--red);\">Danger Zone</div>\n");
      out.write("        <p style=\"font-size:13px;color:var(--text-secondary);margin-bottom:16px;\">\n");
      out.write("          Logging out will end your current session.\n");
      out.write("        </p>\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/user/logout\" class=\"btn btn-danger btn-sm\">⏻ Sign Out</a>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div><!-- /profile-area -->\n");
      out.write("  </div><!-- /main-content -->\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print( ctx );
      out.write("/js/app.js\"></script>\n");
      out.write("<script>\n");
      out.write("// Password match validation\n");
      out.write("document.querySelector('form[action*=\"password\"]').addEventListener('submit', function(e) {\n");
      out.write("  const np = document.getElementById('new-pass').value;\n");
      out.write("  const cp = document.getElementById('confirm-pass').value;\n");
      out.write("  if (np !== cp) {\n");
      out.write("    e.preventDefault();\n");
      out.write("    Toast.error('New passwords do not match!');\n");
      out.write("  }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
