/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2026-04-02 13:55:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.javamail.model.User;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.javamail.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    User __sidebarUser  = (User)  session.getAttribute("user");
    int  __unreadCount  = (request.getAttribute("unread") instanceof Integer)
                         ? (Integer) request.getAttribute("unread") : 0;
    String __folder     = (String) request.getAttribute("folder");
    if (__folder == null) __folder = "";
    String __ctx        = request.getContextPath();

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"sidebar\">\n");
      out.write("  <!-- Logo -->\n");
      out.write("  <div class=\"sidebar-logo\">\n");
      out.write("    <div class=\"sidebar-logo-icon\">✉</div>\n");
      out.write("    <span class=\"sidebar-logo-text\">JavaMail</span>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- Compose button -->\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/mail/compose\" class=\"compose-btn\">\n");
      out.write("    ✏ Compose\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <!-- Folders -->\n");
      out.write("  <span class=\"nav-section-label\">Folders</span>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/mail/inbox\"\n");
      out.write("     class=\"nav-item ");
      out.print( "inbox".equals(__folder) ? "active" : "" );
      out.write("\">\n");
      out.write("    <span class=\"nav-icon\">📥</span> Inbox\n");
      out.write("    ");
 if (__unreadCount > 0) { 
      out.write("<span class=\"nav-badge\">");
      out.print( __unreadCount );
      out.write("</span>");
 } 
      out.write("\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/mail/sent\"\n");
      out.write("     class=\"nav-item ");
      out.print( "sent".equals(__folder) ? "active" : "" );
      out.write("\">\n");
      out.write("    <span class=\"nav-icon\">📤</span> Sent\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/mail/draft\"\n");
      out.write("     class=\"nav-item ");
      out.print( "draft".equals(__folder) ? "active" : "" );
      out.write("\">\n");
      out.write("    <span class=\"nav-icon\">📝</span> Drafts\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/mail/starred\"\n");
      out.write("     class=\"nav-item ");
      out.print( "starred".equals(__folder) ? "active" : "" );
      out.write("\">\n");
      out.write("    <span class=\"nav-icon\">⭐</span> Starred\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/mail/important\"\n");
      out.write("     class=\"nav-item ");
      out.print( "important".equals(__folder) ? "active" : "" );
      out.write("\">\n");
      out.write("    <span class=\"nav-icon\">🔖</span> Important\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <div class=\"sidebar-divider\"></div>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/mail/spam\"\n");
      out.write("     class=\"nav-item ");
      out.print( "spam".equals(__folder) ? "active" : "" );
      out.write("\">\n");
      out.write("    <span class=\"nav-icon\">🚫</span> Spam\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/mail/trash\"\n");
      out.write("     class=\"nav-item ");
      out.print( "trash".equals(__folder) ? "active" : "" );
      out.write("\">\n");
      out.write("    <span class=\"nav-icon\">🗑</span> Trash\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <div class=\"sidebar-divider\"></div>\n");
      out.write("\n");
      out.write("  <!-- Settings -->\n");
      out.write("  <span class=\"nav-section-label\">Account</span>\n");
      out.write("  <a href=\"");
      out.print( __ctx );
      out.write("/user/profile\"\n");
      out.write("     class=\"nav-item ");
      out.print( "profile".equals(__folder) ? "active" : "" );
      out.write("\">\n");
      out.write("    <span class=\"nav-icon\">👤</span> Profile\n");
      out.write("  </a>\n");
      out.write("\n");
      out.write("  <!-- User info + logout -->\n");
      out.write("  <div class=\"sidebar-user\">\n");
      out.write("    <div class=\"sidebar-avatar\"\n");
      out.write("         data-email-avatar=\"");
      out.print( __sidebarUser != null ? __sidebarUser.getEmail() : "" );
      out.write("\"\n");
      out.write("         data-name=\"");
      out.print( __sidebarUser != null ? __sidebarUser.getUsername() : "" );
      out.write("\">\n");
      out.write("      ");
      out.print( __sidebarUser != null ? __sidebarUser.getUsername().substring(0,1).toUpperCase() : "?" );
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"sidebar-user-info\">\n");
      out.write("      <div class=\"sidebar-user-name\">");
      out.print( __sidebarUser != null ? __sidebarUser.getUsername() : "" );
      out.write("</div>\n");
      out.write("      <div class=\"sidebar-user-email\">");
      out.print( __sidebarUser != null ? __sidebarUser.getEmail() : "" );
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("    <a href=\"");
      out.print( __ctx );
      out.write("/user/logout\" class=\"sidebar-logout\" title=\"Logout\">⏻</a>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
